"""
TDD — Carga manual de CRYPTO y REAL_ESTATE.
"""
from decimal import Decimal
from unittest.mock import MagicMock, patch

import pytest

from app.routers.positions import create_manual_position, ManualPositionCreate
from app.models import Position


def _make_db(existing_positions=None):
    db = MagicMock()
    created = []

    def fake_add(obj):
        created.append(obj)

    def fake_commit():
        for obj in created:
            if not hasattr(obj, "id") or obj.id is None:
                obj.id = 99

    db.add.side_effect = fake_add
    db.commit.side_effect = fake_commit
    db.refresh.side_effect = lambda obj: None

    # Para el query de tickers existentes (RESTATE auto-numeración)
    existing = existing_positions or []
    mock_query = MagicMock()
    mock_query.filter.return_value = mock_query
    mock_query.all.return_value = existing
    mock_query.first.return_value = None
    db.query.return_value = mock_query

    return db, created


class TestCryptoManual:

    def test_crypto_uses_coingecko_price(self):
        """Si CoinGecko responde, el precio live se usa como current_price_usd."""
        db, created = _make_db()
        body = ManualPositionCreate(
            asset_type="CRYPTO",
            ticker="BTC",
            description="Bitcoin",
            quantity=0.05,
            purchase_price_usd=80000.0,
            ppc_ars=0.0,
            purchase_fx_rate=0.0,
            external_id="bitcoin",
        )
        with patch("app.routers.positions.crypto_prices.get_price_usd", return_value=85000.0), \
             patch("app.routers.positions.crypto_prices.get_yield_30d", return_value=0.12), \
             patch("app.routers.positions._invalidate_score_cache"):
            create_manual_position(body, db=db, user_id="user-1")

        pos = created[0]
        assert float(pos.current_price_usd) == 85000.0
        assert pos.ticker == "BTC"
        assert pos.asset_type == "CRYPTO"
        assert float(pos.quantity) == 0.05

    def test_crypto_fallback_to_purchase_price_when_coingecko_fails(self):
        """Si CoinGecko falla, se usa el precio de compra."""
        db, created = _make_db()
        body = ManualPositionCreate(
            asset_type="CRYPTO",
            ticker="ETH",
            description="Ethereum",
            quantity=1.0,
            purchase_price_usd=2000.0,
            ppc_ars=0.0,
            purchase_fx_rate=0.0,
            external_id="ethereum",
        )
        with patch("app.routers.positions.crypto_prices.get_price_usd", return_value=None), \
             patch("app.routers.positions.crypto_prices.get_yield_30d", return_value=0.0), \
             patch("app.routers.positions._invalidate_score_cache"):
            create_manual_position(body, db=db, user_id="user-1")

        pos = created[0]
        assert float(pos.current_price_usd) == 2000.0

    def test_crypto_thumb_in_search(self):
        """search_coins retorna el campo thumb para mostrar logo."""
        from app.services.crypto_prices import search_coins
        with patch("app.services.crypto_prices.httpx.get") as mock_get:
            mock_get.return_value.raise_for_status = MagicMock()
            mock_get.return_value.json.return_value = {
                "coins": [
                    {"id": "bitcoin", "name": "Bitcoin", "symbol": "btc",
                     "market_cap_rank": 1, "thumb": "https://assets.coingecko.com/coins/images/1/thumb/bitcoin.png"}
                ]
            }
            results = search_coins("bitcoin")
        assert results[0]["thumb"] == "https://assets.coingecko.com/coins/images/1/thumb/bitcoin.png"
        assert results[0]["symbol"] == "BTC"


class TestRealEstateManual:

    def test_restate_ticker_autogenerated_first(self):
        """Sin inmuebles previos → ticker = RESTATE_1."""
        db, created = _make_db(existing_positions=[])
        body = ManualPositionCreate(
            asset_type="REAL_ESTATE",
            ticker="",  # ignorado — se auto-genera
            description="Av. Corrientes 1234, CABA",
            quantity=1.0,
            purchase_price_usd=120000.0,  # valuación
            ppc_ars=0.0,
            purchase_fx_rate=0.0,
            monthly_rent_usd=600.0,
        )
        with patch("app.routers.positions._invalidate_score_cache"):
            create_manual_position(body, db=db, user_id="user-1")

        pos = created[0]
        assert pos.ticker == "RESTATE_1"
        assert pos.asset_type == "REAL_ESTATE"
        assert float(pos.quantity) == 1.0
        assert float(pos.current_price_usd) == 120000.0  # valuación

    def test_restate_annual_yield_computed_from_rent(self):
        """annual_yield_pct = (monthly_rent * 12) / valuation."""
        db, created = _make_db(existing_positions=[])
        body = ManualPositionCreate(
            asset_type="REAL_ESTATE",
            ticker="",
            description="Depto Palermo",
            quantity=1.0,
            purchase_price_usd=100000.0,
            ppc_ars=0.0,
            purchase_fx_rate=0.0,
            monthly_rent_usd=500.0,
        )
        with patch("app.routers.positions._invalidate_score_cache"):
            create_manual_position(body, db=db, user_id="user-1")

        pos = created[0]
        expected_yield = (500 * 12) / 100000  # 0.06 = 6%
        assert abs(float(pos.annual_yield_pct) - expected_yield) < 0.001

    def test_restate_ticker_sequential_second(self):
        """Con un inmueble previo → ticker = RESTATE_2."""
        prev = MagicMock()
        prev.ticker = "RESTATE_1"
        db, created = _make_db(existing_positions=[prev])
        body = ManualPositionCreate(
            asset_type="REAL_ESTATE",
            ticker="",
            description="Casa en Mendoza",
            quantity=1.0,
            purchase_price_usd=80000.0,
            ppc_ars=0.0,
            purchase_fx_rate=0.0,
            monthly_rent_usd=400.0,
        )
        with patch("app.routers.positions._invalidate_score_cache"):
            create_manual_position(body, db=db, user_id="user-1")

        pos = created[0]
        assert pos.ticker == "RESTATE_2"

    def test_restate_in_freedom_calculator_renta_bucket(self):
        """REAL_ESTATE contribuye al bucket RENTA de freedom_calculator."""
        from app.services.freedom_calculator import split_portfolio_buckets

        class FakePos:
            asset_type = "REAL_ESTATE"
            current_value_usd = Decimal("100000")
            annual_yield_pct = Decimal("0.06")
            source = "MANUAL"

        result = split_portfolio_buckets([FakePos()])
        assert result["renta_monthly_usd"] == pytest.approx(Decimal("500"), abs=Decimal("1"))
        assert result["renta_total_usd"] == Decimal("100000")
        assert result["capital_total_usd"] == Decimal("0")
